spring:
  datasource:
    url: jdbc:sqlserver://azdb.database.windows.net:1433;database=azemployee;user=admin@123@azdb;password=Pass@word1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

